# Generated by Django 3.2.8 on 2022-01-06 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0002_auto_20211026_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nombre', max_length=45)),
                ('estado', models.CharField(help_text='nombre', max_length=45)),
            ],
        ),
        migrations.RenameModel(
            old_name='Manager',
            new_name='Usuario',
        ),
        migrations.DeleteModel(
            name='Temple',
        ),
        migrations.AddField(
            model_name='solicitudpartida',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temples', to='temple.usuario'),
        ),
    ]
