# Generated by Django 3.2.8 on 2022-01-06 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0003_auto_20220105_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudpartida',
            old_name='manager',
            new_name='usuario',
        ),
    ]
