# Generated by Django 3.2.8 on 2022-01-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0004_rename_manager_solicitudpartida_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpartida',
            name='fechaPartida',
            field=models.CharField(default='Some String', max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='Some String', help_text='nombre', max_length=45),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estadoUsuario',
            field=models.CharField(default='Some String', help_text='nombre', max_length=45),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.CharField(default='Some String', help_text='nombre', max_length=45),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='Some String', help_text='nombre', max_length=45),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Some String', help_text='nombre', max_length=45),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='Some String', help_text='nombre', max_length=45),
        ),
        migrations.AlterField(
            model_name='solicitudpartida',
            name='estado',
            field=models.CharField(default='Some String', help_text='estado', max_length=45),
        ),
    ]
