# Generated by Django 3.2.8 on 2022-01-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0005_auto_20220105_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpartida',
            name='estado',
            field=models.CharField(help_text='estado', max_length=45),
        ),
        migrations.AlterField(
            model_name='solicitudpartida',
            name='fechaPartida',
            field=models.CharField(max_length=30),
        ),
    ]
