# Generated by Django 3.2.8 on 2022-01-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0006_auto_20220105_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(help_text='nombre', max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estadoUsuario',
            field=models.CharField(help_text='nombre', max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.CharField(help_text='nombre', max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(help_text='nombre', max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(help_text='nombre', max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(help_text='nombre', max_length=45),
        ),
    ]
