# Generated by Django 3.2.8 on 2022-01-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0007_auto_20220105_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpartida',
            name='fechaPartida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estadoUsuario',
            field=models.BooleanField(default=True, help_text='Estado del usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(help_text='nombre', max_length=10),
        ),
    ]
