# Generated by Django 3.2.8 on 2022-01-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0008_auto_20220105_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpartida',
            name='fechaPartida',
            field=models.DateTimeField(help_text='fecha partida'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='email', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateTimeField(help_text='fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(help_text='password', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(help_text='rol', max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(help_text='telefono', max_length=45),
        ),
    ]
