# Generated by Django 3.2.8 on 2022-01-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0009_auto_20220105_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='telephone',
        ),
    ]
