# Generated by Django 3.2.8 on 2022-01-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0011_alter_solicitudpartida_fechapartida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpartida',
            name='fechaPartida',
            field=models.DateTimeField(help_text='fecha partida'),
        ),
    ]
