# Generated by Django 3.2.8 on 2022-01-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0012_alter_solicitudpartida_fechapartida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpartida',
            name='fechaPartida',
            field=models.DateField(help_text='fecha partida'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(help_text='fecha nacimiento'),
        ),
    ]
